<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5A3OTB0" failures="2" tests="9" name="Test" time="0.512" errors="0" timestamp="2025-05-12T11:18:34 IST">
  <testcase classname="tests.FailTests" name="passtest1" time="0.052"/>
  <testcase classname="tests.FailTests" name="failtest2" time="0.065">
    <skipped/>
  </testcase> <!-- failtest2 -->
  <testcase classname="tests.FailTests" name="failtest2" time="0.011">
    <skipped/>
  </testcase> <!-- failtest2 -->
  <testcase classname="tests.FailTests" name="failtest2" time="0.005">
    <skipped/>
  </testcase> <!-- failtest2 -->
  <testcase classname="tests.FailTests" name="failtest2" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.FailTests.failtest2(FailTests.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- failtest2 -->
  <testcase classname="tests.FailTests" name="failtest1" time="0.012">
    <skipped/>
  </testcase> <!-- failtest1 -->
  <testcase classname="tests.FailTests" name="failtest1" time="0.009">
    <skipped/>
  </testcase> <!-- failtest1 -->
  <testcase classname="tests.FailTests" name="failtest1" time="0.012">
    <skipped/>
  </testcase> <!-- failtest1 -->
  <testcase classname="tests.FailTests" name="failtest1" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.FailTests.failtest1(FailTests.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- failtest1 -->
</testsuite> <!-- Test -->
